### ISSUE TITLE
Switching from Z3 4.8.5 to 4.8.6 leads to major issues

### ISSUE THREAD

**Issue by zvonimir** [boogie-org/corral#110]
I am using the latest release of Corral (release 1.0.2). I just noticed that moving from  Z3 4.8.5 to 4.8.6 (and also 4.8.7) leads to an explosion of exception of the kind:
```
Unhandled exception. CoreLib.InsufficientDetailsToConstructCexPath: StratifiedInliningErrorReporter: Must find a successor
   at CoreLib.StratifiedInliningErrorReporter.GetAbsyTraceLabels(StratifiedVC svc, IList`1 labels) in /home/travis/build/boogie-org/corral/source/CoreLib/StratifiedInlining.cs:line 4195
   at CoreLib.StratifiedInliningErrorReporter.GetAbsyTrace(StratifiedVC svc, IList`1 labels) in /home/travis/build/boogie-org/corral/source/CoreLib/StratifiedInlining.cs:line 4190
...
```
We occasionally observe such exceptions (typically when running on large programs), but with this Z3 update they occur in many of our regressions (even smaller ones), all of which were passing before.

**Comment by akashlal** [comment]
What flags are you using? This exception means that Corral was not able to construct a counterexample path from the Z3 model. It might be due to incompleteness (e.g., in the presence of quantifiers) or maybe the labels support in Z3 is going away. Are you using `/doNotUseLabels`?

**Comment by zvonimir** [comment]
Sorry, my pull request "fixes" the problem it seems. I forgot to close this.
